# Make sure to check the documentation at https://goreleaser.com
project_name: cli-plugin-gcp
before:
  hooks:
    - go mod tidy
builds:
  - id: "gcp"
    tags:
      - "gcp"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X main.version={{.Version}}
  - id: "bigquery"
    tags:
      - "bigquery"
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    ldflags:
      - -X main.version={{.Version}}

checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
archives:
  - id: "gcp"
    builds:
      - "gcp"
    format: 'tar.gz'
    name_template: '{{ .ProjectName }}-gcp-{{ .Version }}-{{ .Os }}_{{ .Arch }}'
  - id: "bigquery"
    builds:
      - "bigquery"
    format: 'tar.gz'
    name_template: '{{ .ProjectName }}-bigquery-{{ .Version }}-{{ .Os }}_{{ .Arch }}'
  - id: "backwards-compatible-gcp"
    builds:
    - "gcp"
    format: 'tar.gz'
    name_template: '{{ .ProjectName }}-{{ .Version }}-{{ .Os }}_{{ .Arch }}'
release:
  prerelease: auto