GO := go

gotestsum := go run gotest.tools/gotestsum@latest

generate:
	go get github.com/raito-io/enumer
	go generate ./...

build: generate
	go build -tags gcp ./...
	go build -tags bigquery ./...

unit-test:
	$(gotestsum) --debug --format pkgname -- -mod=readonly -coverpkg=./... -covermode=atomic -coverprofile=unit-test-coverage.txt ./...

lint:
	golangci-lint run --build-tags gcp ./...
	golangci-lint run --build-tags bigquery ./...
	go fmt ./...

test:
	$(gotestsum) --debug --format pkgname -- -mod=readonly -tags=integration -race -coverpkg=./... -covermode=atomic -coverprofile=coverage.out.tmp ./...
	cat coverage.out.tmp | grep -v "/mock_" > coverage.txt #IGNORE MOCKS
	go tool cover -html=coverage.txt -o coverage.html
