// Code generated by mockery v2.39.1. DO NOT EDIT.

package org

import (
	context "context"

	iam "github.com/raito-io/cli-plugin-gcp/internal/iam"
	mock "github.com/stretchr/testify/mock"
)

// mockOrganizationRepo is an autogenerated mock type for the organizationRepo type
type mockOrganizationRepo struct {
	mock.Mock
}

type mockOrganizationRepo_Expecter struct {
	mock *mock.Mock
}

func (_m *mockOrganizationRepo) EXPECT() *mockOrganizationRepo_Expecter {
	return &mockOrganizationRepo_Expecter{mock: &_m.Mock}
}

// GetIamPolicy provides a mock function with given fields: ctx, projectId
func (_m *mockOrganizationRepo) GetIamPolicy(ctx context.Context, projectId string) ([]iam.IamBinding, error) {
	ret := _m.Called(ctx, projectId)

	if len(ret) == 0 {
		panic("no return value specified for GetIamPolicy")
	}

	var r0 []iam.IamBinding
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]iam.IamBinding, error)); ok {
		return rf(ctx, projectId)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []iam.IamBinding); ok {
		r0 = rf(ctx, projectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]iam.IamBinding)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, projectId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOrganizationRepo_GetIamPolicy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetIamPolicy'
type mockOrganizationRepo_GetIamPolicy_Call struct {
	*mock.Call
}

// GetIamPolicy is a helper method to define mock.On call
//   - ctx context.Context
//   - projectId string
func (_e *mockOrganizationRepo_Expecter) GetIamPolicy(ctx interface{}, projectId interface{}) *mockOrganizationRepo_GetIamPolicy_Call {
	return &mockOrganizationRepo_GetIamPolicy_Call{Call: _e.mock.On("GetIamPolicy", ctx, projectId)}
}

func (_c *mockOrganizationRepo_GetIamPolicy_Call) Run(run func(ctx context.Context, projectId string)) *mockOrganizationRepo_GetIamPolicy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *mockOrganizationRepo_GetIamPolicy_Call) Return(_a0 []iam.IamBinding, _a1 error) *mockOrganizationRepo_GetIamPolicy_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOrganizationRepo_GetIamPolicy_Call) RunAndReturn(run func(context.Context, string) ([]iam.IamBinding, error)) *mockOrganizationRepo_GetIamPolicy_Call {
	_c.Call.Return(run)
	return _c
}

// GetOrganization provides a mock function with given fields: ctx
func (_m *mockOrganizationRepo) GetOrganization(ctx context.Context) (*GcpOrgEntity, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetOrganization")
	}

	var r0 *GcpOrgEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*GcpOrgEntity, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *GcpOrgEntity); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*GcpOrgEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockOrganizationRepo_GetOrganization_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOrganization'
type mockOrganizationRepo_GetOrganization_Call struct {
	*mock.Call
}

// GetOrganization is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockOrganizationRepo_Expecter) GetOrganization(ctx interface{}) *mockOrganizationRepo_GetOrganization_Call {
	return &mockOrganizationRepo_GetOrganization_Call{Call: _e.mock.On("GetOrganization", ctx)}
}

func (_c *mockOrganizationRepo_GetOrganization_Call) Run(run func(ctx context.Context)) *mockOrganizationRepo_GetOrganization_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *mockOrganizationRepo_GetOrganization_Call) Return(_a0 *GcpOrgEntity, _a1 error) *mockOrganizationRepo_GetOrganization_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockOrganizationRepo_GetOrganization_Call) RunAndReturn(run func(context.Context) (*GcpOrgEntity, error)) *mockOrganizationRepo_GetOrganization_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBinding provides a mock function with given fields: ctx, dataObject, bindingsToAdd, bindingsToDelete
func (_m *mockOrganizationRepo) UpdateBinding(ctx context.Context, dataObject *iam.DataObjectReference, bindingsToAdd []iam.IamBinding, bindingsToDelete []iam.IamBinding) error {
	ret := _m.Called(ctx, dataObject, bindingsToAdd, bindingsToDelete)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBinding")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *iam.DataObjectReference, []iam.IamBinding, []iam.IamBinding) error); ok {
		r0 = rf(ctx, dataObject, bindingsToAdd, bindingsToDelete)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockOrganizationRepo_UpdateBinding_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBinding'
type mockOrganizationRepo_UpdateBinding_Call struct {
	*mock.Call
}

// UpdateBinding is a helper method to define mock.On call
//   - ctx context.Context
//   - dataObject *iam.DataObjectReference
//   - bindingsToAdd []iam.IamBinding
//   - bindingsToDelete []iam.IamBinding
func (_e *mockOrganizationRepo_Expecter) UpdateBinding(ctx interface{}, dataObject interface{}, bindingsToAdd interface{}, bindingsToDelete interface{}) *mockOrganizationRepo_UpdateBinding_Call {
	return &mockOrganizationRepo_UpdateBinding_Call{Call: _e.mock.On("UpdateBinding", ctx, dataObject, bindingsToAdd, bindingsToDelete)}
}

func (_c *mockOrganizationRepo_UpdateBinding_Call) Run(run func(ctx context.Context, dataObject *iam.DataObjectReference, bindingsToAdd []iam.IamBinding, bindingsToDelete []iam.IamBinding)) *mockOrganizationRepo_UpdateBinding_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*iam.DataObjectReference), args[2].([]iam.IamBinding), args[3].([]iam.IamBinding))
	})
	return _c
}

func (_c *mockOrganizationRepo_UpdateBinding_Call) Return(_a0 error) *mockOrganizationRepo_UpdateBinding_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockOrganizationRepo_UpdateBinding_Call) RunAndReturn(run func(context.Context, *iam.DataObjectReference, []iam.IamBinding, []iam.IamBinding) error) *mockOrganizationRepo_UpdateBinding_Call {
	_c.Call.Return(run)
	return _c
}

// newMockOrganizationRepo creates a new instance of mockOrganizationRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockOrganizationRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockOrganizationRepo {
	mock := &mockOrganizationRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
