// Code generated by mockery v2.40.1. DO NOT EDIT.

package org

import (
	context "context"

	data_source "github.com/raito-io/cli/base/data_source"
	mock "github.com/stretchr/testify/mock"
)

// mockGcpDataIterator is an autogenerated mock type for the gcpDataIterator type
type mockGcpDataIterator struct {
	mock.Mock
}

type mockGcpDataIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockGcpDataIterator) EXPECT() *mockGcpDataIterator_Expecter {
	return &mockGcpDataIterator_Expecter{mock: &_m.Mock}
}

// DataObjects provides a mock function with given fields: ctx, config, fn
func (_m *mockGcpDataIterator) DataObjects(ctx context.Context, config *data_source.DataSourceSyncConfig, fn func(context.Context, *GcpOrgEntity) error) error {
	ret := _m.Called(ctx, config, fn)

	if len(ret) == 0 {
		panic("no return value specified for DataObjects")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *data_source.DataSourceSyncConfig, func(context.Context, *GcpOrgEntity) error) error); ok {
		r0 = rf(ctx, config, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockGcpDataIterator_DataObjects_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DataObjects'
type mockGcpDataIterator_DataObjects_Call struct {
	*mock.Call
}

// DataObjects is a helper method to define mock.On call
//   - ctx context.Context
//   - config *data_source.DataSourceSyncConfig
//   - fn func(context.Context , *GcpOrgEntity) error
func (_e *mockGcpDataIterator_Expecter) DataObjects(ctx interface{}, config interface{}, fn interface{}) *mockGcpDataIterator_DataObjects_Call {
	return &mockGcpDataIterator_DataObjects_Call{Call: _e.mock.On("DataObjects", ctx, config, fn)}
}

func (_c *mockGcpDataIterator_DataObjects_Call) Run(run func(ctx context.Context, config *data_source.DataSourceSyncConfig, fn func(context.Context, *GcpOrgEntity) error)) *mockGcpDataIterator_DataObjects_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*data_source.DataSourceSyncConfig), args[2].(func(context.Context, *GcpOrgEntity) error))
	})
	return _c
}

func (_c *mockGcpDataIterator_DataObjects_Call) Return(_a0 error) *mockGcpDataIterator_DataObjects_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockGcpDataIterator_DataObjects_Call) RunAndReturn(run func(context.Context, *data_source.DataSourceSyncConfig, func(context.Context, *GcpOrgEntity) error) error) *mockGcpDataIterator_DataObjects_Call {
	_c.Call.Return(run)
	return _c
}

// newMockGcpDataIterator creates a new instance of mockGcpDataIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockGcpDataIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockGcpDataIterator {
	mock := &mockGcpDataIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
