name: "Generate infrastructure"
description: "Generate infrastructure"
inputs:
  gcpProject:
    description: "GCP project name"
    required: true
  gcpRegion:
    description: "GCP region"
    required: true
  gcpCredentials:
    description: "GCP credentials"
    required: true
  emailStewartB:
    description: "B Stewart's email"
    required: true
  emailHarrisC:
    description: "C Harris's email"
    required: true
  emailHaydenD:
    description: "D Hayden's email"
    required: true
  emailCarissaM:
    description: "M Carissa's email"
    required: true
  emailNguyenN:
    description: "N Nguyen's email"
    required: true
  emailGroupSales:
    description: "Sales group email"
    required: true
  emailGroupDev:
    description: "Engineering group email"
    required: true
  testingDataset:
    description: "Indicate if testing dataset should be generated"
    required: false
    default: 'false'
  demoDataset:
    description: "Indicate if demo dataset should be generated"
    required: false
    default: 'true'

runs:
  using: composite
  steps:
    - name: Generate infra
      shell: bash
      run: make gen-test-infra
      env:
        TF_VAR_gcp_project: ${{ inputs.gcpProject }}
        TF_VAR_gcp_region: ${{ inputs.gcpRegion}}
        TF_VAR_email_b_stewart: ${{ inputs.emailStewartB }}
        TF_VAR_email_c_harris: ${{ inputs.emailHarrisC }}
        TF_VAR_email_d_hayden: ${{ inputs.emailHaydenD }}
        TF_VAR_email_m_carissa: ${{ inputs.emailCarissaM }}
        TF_VAR_email_n_nguyen: ${{ inputs.emailNguyenN }}
        TF_VAR_email_group_sales: ${{ inputs.emailGroupSales }}
        TF_VAR_email_group_dev: ${{ inputs.emailGroupDev }}
        TF_VAR_testing_dataset: ${{ inputs.testingDataset }}
        TF_VAR_demo_dataset: ${{ inputs.demoDataset }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ inputs.gcpCredentials }}