// Code generated by mockery v2.39.1. DO NOT EDIT.

package bigquery

import (
	context "context"

	data_source "github.com/raito-io/cli/base/data_source"
	mock "github.com/stretchr/testify/mock"

	org "github.com/raito-io/cli-plugin-gcp/internal/org"
)

// mockFilteringDataObjectIterator is an autogenerated mock type for the filteringDataObjectIterator type
type mockFilteringDataObjectIterator struct {
	mock.Mock
}

type mockFilteringDataObjectIterator_Expecter struct {
	mock *mock.Mock
}

func (_m *mockFilteringDataObjectIterator) EXPECT() *mockFilteringDataObjectIterator_Expecter {
	return &mockFilteringDataObjectIterator_Expecter{mock: &_m.Mock}
}

// Sync provides a mock function with given fields: ctx, config, skipColumns, fn
func (_m *mockFilteringDataObjectIterator) Sync(ctx context.Context, config *data_source.DataSourceSyncConfig, skipColumns bool, fn func(context.Context, *org.GcpOrgEntity) error) error {
	ret := _m.Called(ctx, config, skipColumns, fn)

	if len(ret) == 0 {
		panic("no return value specified for Sync")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *data_source.DataSourceSyncConfig, bool, func(context.Context, *org.GcpOrgEntity) error) error); ok {
		r0 = rf(ctx, config, skipColumns, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// mockFilteringDataObjectIterator_Sync_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Sync'
type mockFilteringDataObjectIterator_Sync_Call struct {
	*mock.Call
}

// Sync is a helper method to define mock.On call
//   - ctx context.Context
//   - config *data_source.DataSourceSyncConfig
//   - skipColumns bool
//   - fn func(context.Context , *org.GcpOrgEntity) error
func (_e *mockFilteringDataObjectIterator_Expecter) Sync(ctx interface{}, config interface{}, skipColumns interface{}, fn interface{}) *mockFilteringDataObjectIterator_Sync_Call {
	return &mockFilteringDataObjectIterator_Sync_Call{Call: _e.mock.On("Sync", ctx, config, skipColumns, fn)}
}

func (_c *mockFilteringDataObjectIterator_Sync_Call) Run(run func(ctx context.Context, config *data_source.DataSourceSyncConfig, skipColumns bool, fn func(context.Context, *org.GcpOrgEntity) error)) *mockFilteringDataObjectIterator_Sync_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*data_source.DataSourceSyncConfig), args[2].(bool), args[3].(func(context.Context, *org.GcpOrgEntity) error))
	})
	return _c
}

func (_c *mockFilteringDataObjectIterator_Sync_Call) Return(_a0 error) *mockFilteringDataObjectIterator_Sync_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *mockFilteringDataObjectIterator_Sync_Call) RunAndReturn(run func(context.Context, *data_source.DataSourceSyncConfig, bool, func(context.Context, *org.GcpOrgEntity) error) error) *mockFilteringDataObjectIterator_Sync_Call {
	_c.Call.Return(run)
	return _c
}

// newMockFilteringDataObjectIterator creates a new instance of mockFilteringDataObjectIterator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockFilteringDataObjectIterator(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockFilteringDataObjectIterator {
	mock := &mockFilteringDataObjectIterator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
