// Code generated by mockery v2.36.1. DO NOT EDIT.

package bigquery

import (
	context "context"

	config "github.com/raito-io/cli/base/util/config"

	mock "github.com/stretchr/testify/mock"
)

// mockDataSourceRepository is an autogenerated mock type for the dataSourceRepository type
type mockDataSourceRepository struct {
	mock.Mock
}

type mockDataSourceRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *mockDataSourceRepository) EXPECT() *mockDataSourceRepository_Expecter {
	return &mockDataSourceRepository_Expecter{mock: &_m.Mock}
}

// GetDataSets provides a mock function with given fields: ctx, configMap
func (_m *mockDataSourceRepository) GetDataSets(ctx context.Context, configMap *config.ConfigMap) ([]BQEntity, error) {
	ret := _m.Called(ctx, configMap)

	var r0 []BQEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.ConfigMap) ([]BQEntity, error)); ok {
		return rf(ctx, configMap)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.ConfigMap) []BQEntity); ok {
		r0 = rf(ctx, configMap)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BQEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.ConfigMap) error); ok {
		r1 = rf(ctx, configMap)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDataSourceRepository_GetDataSets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDataSets'
type mockDataSourceRepository_GetDataSets_Call struct {
	*mock.Call
}

// GetDataSets is a helper method to define mock.On call
//   - ctx context.Context
//   - configMap *config.ConfigMap
func (_e *mockDataSourceRepository_Expecter) GetDataSets(ctx interface{}, configMap interface{}) *mockDataSourceRepository_GetDataSets_Call {
	return &mockDataSourceRepository_GetDataSets_Call{Call: _e.mock.On("GetDataSets", ctx, configMap)}
}

func (_c *mockDataSourceRepository_GetDataSets_Call) Run(run func(ctx context.Context, configMap *config.ConfigMap)) *mockDataSourceRepository_GetDataSets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.ConfigMap))
	})
	return _c
}

func (_c *mockDataSourceRepository_GetDataSets_Call) Return(_a0 []BQEntity, _a1 error) *mockDataSourceRepository_GetDataSets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDataSourceRepository_GetDataSets_Call) RunAndReturn(run func(context.Context, *config.ConfigMap) ([]BQEntity, error)) *mockDataSourceRepository_GetDataSets_Call {
	_c.Call.Return(run)
	return _c
}

// GetTables provides a mock function with given fields: ctx, configMap, parent
func (_m *mockDataSourceRepository) GetTables(ctx context.Context, configMap *config.ConfigMap, parent BQEntity) ([]BQEntity, error) {
	ret := _m.Called(ctx, configMap, parent)

	var r0 []BQEntity
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *config.ConfigMap, BQEntity) ([]BQEntity, error)); ok {
		return rf(ctx, configMap, parent)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *config.ConfigMap, BQEntity) []BQEntity); ok {
		r0 = rf(ctx, configMap, parent)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]BQEntity)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *config.ConfigMap, BQEntity) error); ok {
		r1 = rf(ctx, configMap, parent)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// mockDataSourceRepository_GetTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetTables'
type mockDataSourceRepository_GetTables_Call struct {
	*mock.Call
}

// GetTables is a helper method to define mock.On call
//   - ctx context.Context
//   - configMap *config.ConfigMap
//   - parent BQEntity
func (_e *mockDataSourceRepository_Expecter) GetTables(ctx interface{}, configMap interface{}, parent interface{}) *mockDataSourceRepository_GetTables_Call {
	return &mockDataSourceRepository_GetTables_Call{Call: _e.mock.On("GetTables", ctx, configMap, parent)}
}

func (_c *mockDataSourceRepository_GetTables_Call) Run(run func(ctx context.Context, configMap *config.ConfigMap, parent BQEntity)) *mockDataSourceRepository_GetTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*config.ConfigMap), args[2].(BQEntity))
	})
	return _c
}

func (_c *mockDataSourceRepository_GetTables_Call) Return(_a0 []BQEntity, _a1 error) *mockDataSourceRepository_GetTables_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *mockDataSourceRepository_GetTables_Call) RunAndReturn(run func(context.Context, *config.ConfigMap, BQEntity) ([]BQEntity, error)) *mockDataSourceRepository_GetTables_Call {
	_c.Call.Return(run)
	return _c
}

// newMockDataSourceRepository creates a new instance of mockDataSourceRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockDataSourceRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockDataSourceRepository {
	mock := &mockDataSourceRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
