name: Raito CLI - GCP Plugin - Build
on:
  push:
    branches:
      - 'main'
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
          cache: true

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: make build

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.55.1

      - name: Generate credentials file
        run: | 
          echo $GCP_CREDENTIALS > credentials.json
          echo $(pwd)/credentials.json >> $GOOGLE_APPLICATION_CREDENTIALS
        env:
          GCP_CREDENTIALS: ${{ secrets.gcp_credentials }}

      - name: Test
        run: make test
        env:
          GSUITE_CUSTOMER_ID: ${{ secrets.gsuite_customer_id }}
          GSUITE_IMPERSONATE_SUBJECT: ${{ secrets.gsuite_impersonate_subject }}

      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.txt
